<?php
/**
 * @var string $temp_key
 */

return apply_filters( 'VC_PAGE_BUILDER_FILTER_IMAGE_BLOCKS', [
    'key' => $temp_key . 'img_blocks_group',
    'name' => 'image_block',
    'label' => 'Image Blocks',
    'display' => 'row',
    'sub_fields' => [
        [
            'key' => $temp_key . 'img_blocks_title',
            'label' => 'Title',
            'name' => 'title',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ],
        [
            'key' => $temp_key . 'img_blocks_blocks',
            'label' => 'Blocks',
            'name' => 'blocks',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'collapsed' => '',
            'min' => 1,
            //One column layouts allow for a max of 4 images. Other columns can only have 1.
            'max' => strpos( $temp_key, VC_PAGE_BUILDER_COLUMN_ONE ) === false ? 1 : 4,
            'layout' => 'block',
            'button_label' => 'Add Image Block',
            'sub_fields' => [
                [
                    'key' => $temp_key . 'img_blocks_block_image',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ],
                [
                    'key' => $temp_key . 'img_blocks_block_title',
                    'label' => 'Title',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ],
                [
                    'key' => $temp_key . 'img_blocks_block_wysiwyg',
                    'label' => 'Wysiwyg',
                    'name' => 'wysiwyg',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                ],
                [
                    'key' => $temp_key . 'img_blocks_block_link',
                    'label' => 'Link',
                    'name' => 'link',
                    'type' => 'page_link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'post_type' => [],
                    'taxonomy' => [],
                    'allow_null' => 0,
                    'allow_archives' => 1,
                    'multiple' => 0,
                ],
            ],
        ],
    ],
    'min' => '',
    'max' => '',
]);