<?php
/**
 * @var string $temp_key
 */

use \VC\PageBuilder\Core;

return apply_filters( 'VC_PAGE_BUILDER_FILTER_TESTIMONIAL_PANELS', [
    'key' => $temp_key . '_tpg',
    'name' => 'testimonial_panels',
    'label' => 'Testimonial Panels',
    'display' => 'block',
    'sub_fields' => [
        [
            'key' =>  $temp_key . '_panel_repeater',
            'label' => 'Panel',
            'name' => 'panel',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'collapsed' => '',
            'min' => 1,
            'max' => 6,
            'layout' => 'block',
            'button_label' => 'Add Testimonials',
            'sub_fields' => [
                [
                    'key' => $temp_key . '_tpg_top_title',
                    'label' => 'Top Title',
                    'name' => 'top_title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ],
                [
                    'key' => $temp_key . '_tpg_top_subtitle',
                    'label' => 'Top Subtitle',
                    'name' => 'top_subtitle',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ],
                [
                    'key' => $temp_key . '_tpg_wysiwyg',
                    'label' => 'Wysiwyg',
                    'name' => 'wysiwyg',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                ],
                [
                    'key' => $temp_key . '_tpg_bottom_title',
                    'label' => 'Bottom Title',
                    'name' => 'bottom_title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ],
                [
                    'key' => $temp_key . '_tpg_bottom_subtitle',
                    'label' => 'Bottom Subtitle',
                    'name' => 'bottom_subtitle',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ],
                [

                    'key' => $temp_key . '_tpg_image',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ],
                [
                    'key' => $temp_key . '_tpg_full_bleed_image',
                    'label' => 'Full Bleed Image',
                    'name' => 'full_bleed_image',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ],
                8 => Core\load_element('button', ['temp_key' => $temp_key . '_tpg']),
            ],
        ],
    ],
    'min' => '',
    'max' => '',
] );